INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Alan','Moses Schwartz','02-05-59','dolor.dapibus@auctornuncnulla.co.uk','Morbi','True');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Evan','Adrian Yates','02-01-31','eget.metus.In@quismassa.co.uk','Quisque','True');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Fulton','Hamish Woodard','02-06-90','amet.risus.Donec@molestiein.com','ipsum','True');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png.','David','Harding Duran','06-04-60','Suspendisse.sed.dolor@lobortis.edu','amet,','True');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Barry','Blake Herrera','02-23-20','commodo.hendrerit.Donec@Pellentesquehabitantmorbi.ca','Nunc','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Leonard','Salvador Giles','01-06-44','velit.Aliquam.nisl@elit.edu','ridiculus','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Felix','Paki Galloway','10-10-33','id.blandit.at@ettristiquepellentesque.ca','facilisis.','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Robert','Bevis Blankenship','02-24-81','Quisque@nibh.ca','ridiculus','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Cyrus','Victor Perez','11-20-85','facilisis@nibhDonecest.org','sem','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Igor','Cole Rich','10-29-37','dictum.sapien.Aenean@nunc.ca','primis','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Ishmael','Aaron Hurley','01-19-65','at@quis.org','ac','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Ray','Owen Conrad','09-14-43','ante@veliteget.ca','vehicula','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Malik','Jermaine Guthrie','07-02-69','Nulla.semper@utpharetrased.co.uk','Fusce','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Nigel','Hayden Giles','10-29-60','congue.a@in.ca','consectetuer','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Isaiah','Raphael Garza','02-03-87','at.arcu.Vestibulum@Cumsociisnatoque.net','augue,','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Myles','Lane Hicks','11-10-78','nec.imperdiet.nec@Nullamfeugiatplacerat.com','nulla','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Galvin','Anthony Hopkins','03-24-23','massa@Sedpharetrafelis.co.uk','semper','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Maxwell','Jonas Pickett','07-13-81','Integer.vulputate.risus@id.org','gravida','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Grady','Kane Jarvis','08-18-91','Quisque@condimentumDonecat.org','euismod','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Zephania','Otto Bradshaw','12-29-26','lobortis.augue.scelerisque@quisurna.net','Duis','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Dalton','Gregory Cash','01-16-44','dignissim.pharetra.Nam@neque.net','malesuada','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Randall','Thane Johnson','11-25-17','Fusce@sapienNunc.co.uk','parturient','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Colorado','Garth Bartlett','01-28-78','eu.augue.porttitor@egestasSed.org','dui','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Louis','Keaton Sanders','11-26-16','mauris@metusurnaconvallis.org','congue.','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Thor','Dominic Petersen','04-25-58','ac.feugiat@blanditviverra.org','ut','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Victor','Ulysses Terrell','08-05-85','fames@nislarcu.com','interdum','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Ralph','Samuel Alexander','05-14-37','nec@tincidunt.net','nec','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Murphy','Xander Barnett','11-20-44','lacus.Mauris@at.edu','elementum,','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Lyle','Eric Preston','12-30-20','Etiam.bibendum@nullaDonec.org','cursus','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Dante','Lamar Atkinson','02-22-60','dui.in.sodales@tellus.ca','eu','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Lucas','Nolan Sims','07-15-12','erat.vel@magnisdisparturient.edu','iaculis','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Amir','Rajah Love','11-17-34','pellentesque.tellus@diamPellentesquehabitant.net','et','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Laith','Carson Jarvis','09-15-26','mus@litoratorquentper.ca','eu','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Noah','Plato Bruce','11-18-54','Donec.feugiat@turpisegestas.org','metus','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Colt','Zahir Clarke','06-02-73','sem.egestas@adipiscingMauris.net','lorem','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Abbot','Erich Clayton','04-20-28','eleifend@maurisSuspendisse.com','et','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Mannix','Jerry Chapman','03-03-34','pede@sodalesat.net','mus.','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Callum','Justin Oliver','08-18-55','nisl.Maecenas.malesuada@nectellusNunc.edu','ipsum','False');
INSERT INTO "signed_user" (photo,username,name,date_of_birth,email,password,admin) VALUES ('img/user_pic.png','Hall','Beck Ochoa','05-10-72','lorem.luctus@neque.org','Fusce','False');
INSERT INTO "signed_user" (username,name,date_of_birth,email,password,admin) VALUES ('janeDoe','Jane Doe','1984-05-17','mymotherisacriminal@gmail.com','$2y$10$nyBfGFHpBpKC8d4TSajYXe1il9GoKNT2SbpSVE7DIpXE4vc5piADi','False');


INSERT INTO "movie" (title,year,photo) VALUES ('Lion King','1994','img/lionkingposter.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('Pulp Fiction','1994','img/pulpfiction.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('The Lord of the Rings','2003','img/lordoftheringsposter.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('Forrest Gump','1995','img/forrestgumpposter.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('Toy Story','1997','img/toystoryposter.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('Interstellar','2012','img/interstellarposter.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('Roma','2019','img/romaposter.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('Star Wars','2019','img/starwarsposter.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('Coco','2018','img/cocoposter.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('Fight Club','1999','img/fightclubposter.jpg');
INSERT INTO "movie" (title,year,photo) VALUES ('The Godfather ','1972','img/thegodfatherposter.jpg');




INSERT INTO "genre" (genre) VALUES ('Action');
INSERT INTO "genre" (genre) VALUES ('Drama');
INSERT INTO "genre" (genre) VALUES ('Comedy');
INSERT INTO "genre" (genre) VALUES ('Horror');
INSERT INTO "genre" (genre) VALUES ('Fantasy');
INSERT INTO "genre" (genre) VALUES ('Romance');
INSERT INTO "genre" (genre) VALUES ('Thriller');

INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (2,1);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (1,2);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (5,3);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (3,4);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (3,5);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (1,6);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (6,7);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (5,8);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (3,9);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (1,10);
INSERT INTO "movie_genre" (genre_id,movie_id) VALUES (2,10);

INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (2,10);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (2,11);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (2,12);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (2,13);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (2,14);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (2,15);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (2,16);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (2,17);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (1,21);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (2,22);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (3,23);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (4,24);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (5,25);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (6,26);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (7,27);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (8,28);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (9,29);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (10,30);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (11,31);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (12,32);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (13,33);
INSERT INTO "friend" (signed_user_id1,signed_user_id2) VALUES (14,34);

INSERT INTO "group" (title,description,photo,admin) VALUES ('Nice People','Really nice group','Photo',39);
INSERT INTO "group" (title,description,photo,admin) VALUES ('Theodens Riders','Trying to find out where Gondor was when the westfold fell','Photo',38);
INSERT INTO "group" (title,description,photo,admin) VALUES ('SIMBAlino','I just cant wait.. to be admin','Photo',37);
INSERT INTO "group" (title,description,photo,admin) VALUES ('Os Padrinhos (De Crisma)','Were gonna make you an offer you cant refuse','Photo',36);
INSERT INTO "group" (title,description,photo,admin) VALUES ('Gatinhos','Cute cat pics','Photo',35);

INSERT INTO "group_member" (group_id,user_id) VALUES (1,39);
INSERT INTO "group_member" (group_id,user_id) VALUES (1,1);
INSERT INTO "group_member" (group_id,user_id) VALUES (1,2);
INSERT INTO "group_member" (group_id,user_id) VALUES (1,3);
INSERT INTO "group_member" (group_id,user_id) VALUES (1,4);
INSERT INTO "group_member" (group_id,user_id) VALUES (1,5);
INSERT INTO "group_member" (group_id,user_id) VALUES (2,38);
INSERT INTO "group_member" (group_id,user_id) VALUES (2,6);
INSERT INTO "group_member" (group_id,user_id) VALUES (2,7);
INSERT INTO "group_member" (group_id,user_id) VALUES (2,8);
INSERT INTO "group_member" (group_id,user_id) VALUES (2,9);
INSERT INTO "group_member" (group_id,user_id) VALUES (2,10);
INSERT INTO "group_member" (group_id,user_id) VALUES (3,37);
INSERT INTO "group_member" (group_id,user_id) VALUES (3,11);
INSERT INTO "group_member" (group_id,user_id) VALUES (3,12);
INSERT INTO "group_member" (group_id,user_id) VALUES (3,13);
INSERT INTO "group_member" (group_id,user_id) VALUES (3,14);
INSERT INTO "group_member" (group_id,user_id) VALUES (3,15);
INSERT INTO "group_member" (group_id,user_id) VALUES (4,36);
INSERT INTO "group_member" (group_id,user_id) VALUES (4,16);
INSERT INTO "group_member" (group_id,user_id) VALUES (4,17);
INSERT INTO "group_member" (group_id,user_id) VALUES (4,18);
INSERT INTO "group_member" (group_id,user_id) VALUES (4,19);
INSERT INTO "group_member" (group_id,user_id) VALUES (4,20);
INSERT INTO "group_member" (group_id,user_id) VALUES (5,35);
INSERT INTO "group_member" (group_id,user_id) VALUES (5,21);
INSERT INTO "group_member" (group_id,user_id) VALUES (5,22);
INSERT INTO "group_member" (group_id,user_id) VALUES (5,23);
INSERT INTO "group_member" (group_id,user_id) VALUES (5,24);
INSERT INTO "group_member" (group_id,user_id) VALUES (5,25);

INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Great movie', 'Really good movie',1,1);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Great movie', 'This is a film that can entertain anyone young or old, I usually dont care for animated movies but this film is the real deal, this is one of disney best animated movies. The animation is top notch and flawless. This film also features superb work from the vocal cast James Earl Jones, Jeremy Irons, Whoopi Goldberg. This is a standout.',1,2);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Wow', 'I rank this animated film among the great films I have ever seen. It was part of my childhood and it is a film experience I will never forget. And hopefully, you wont either. A++',1,3);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Great movie', 'Best thing ever',1,4);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Amazin movie', 'Amazing  movie',1,5);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Best movie', 'Is there any character called Nala??',1,6);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Yeah....', 'Better than the 2019 version',1,7);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Great movie', 'Why do theu need to fight?',1,8);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Old movie', 'My mother was 20 when it came out',1,9);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Nop', 'My bird likes it',1,10);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Awful movie', 'Awful',1,11);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Not Great', 'Liked toy story better',1,12);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Came for the fight scenes', 'Stayed for Samuel L Jackson',2,2);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Best movie ever', 'Its really long tho',3,3);
INSERT INTO "review" (title,text,movie_id,user_id) VALUES ('Perfect movie except for Jenny', 'Forrest is really funny',4,4);

INSERT INTO "like" (user_id,review_id) VALUES (2,1);
INSERT INTO "like" (user_id,review_id) VALUES (3,1);
INSERT INTO "like" (user_id,review_id) VALUES (7,2);
INSERT INTO "like" (user_id,review_id) VALUES (8,2);
INSERT INTO "like" (user_id,review_id) VALUES (14,3);
INSERT INTO "like" (user_id,review_id) VALUES (16,4);
INSERT INTO "like" (user_id,review_id) VALUES (19,4);

INSERT INTO "comment" (text,signed_user_id,review_id) VALUES ('I Totally agree, but your review could be a little longer',5,1);
INSERT INTO "comment" (text,signed_user_id,review_id) VALUES ('How dare you make a review about Pulp Fiction and only mention Samuel L Jackson',8,2);
INSERT INTO "comment" (text,signed_user_id,review_id) VALUES ('I totally fell asleep while watching it. xD. lol. #aintgotnotimeforthat',14,3);
INSERT INTO "comment" (text,signed_user_id,review_id) VALUES ('Jenny is a complex character and i just cant understand the hate she gets in this site',18,3);

INSERT INTO "rating" (rating,movie_id,user_id) VALUES (10,1,1);
INSERT INTO "rating" (rating,movie_id,user_id) VALUES (8,1,2);
INSERT INTO "rating" (rating,movie_id,user_id) VALUES (9,1,3);
INSERT INTO "rating" (rating,movie_id,user_id) VALUES (7,4,4);
INSERT INTO "rating" (rating,movie_id,user_id) VALUES (8,1,5);
INSERT INTO "rating" (rating,movie_id,user_id) VALUES (10,10,6);
INSERT INTO "rating" (rating,movie_id,user_id) VALUES (9,3,7);
INSERT INTO "rating" (rating,movie_id,user_id) VALUES (9,2,8);
INSERT INTO "rating" (rating,movie_id,user_id) VALUES (8,5,9);
INSERT INTO "rating" (rating,movie_id,user_id) VALUES (8,2,10);

